### ISSUE TITLE
template for block creator node

### ISSUE THREAD

**Issue by zaibon** [threefoldtoken/0-templates#1]

**Comment by LeeSmet** [comment]
## Setting up the daemon

The following assumes the daemon name is `tfchaind` and the client name is `tfchainc`

Command to start the block creator daemon: `tfchaind`. This starts a daemon with all required modules. The http api (used by the client) will only listen on localhost. By default, the tfchain daemon uses port `23112` for its rpc calls (this needs to be exposed globally for outside connections), and port `23110` for the http port used by the api.

These ports can be changed using flags:
```
--rpc-addr string            which port the gateway listens on (default ":23112")
--api-addr string            which host:port the API server listens on (default "localhost:23110")
```

If the api-addr is changed to a non localhost address, it MUST be password protected (usefull to expose api over e.g. a ZT network)

```
--authenticate-api           enable API password protection
--disable-api-security       allow tfchaind to listen on a non-localhost address (DANGEROUS)
```

Passing these flags allows a daemon to make its http port listen on a non localhost address. In this case, the password will be prompted once the daemon is started, and must be entered on stdin

## Unlocking (and loading) the daemon wallet

In order to create blocks, the daemon must have an unlocked wallet which contains blockstakes

For this purpose, the client (`tfchainc`) can be used
I am assuming the client is invoked on the same machine as the daemon. If this is not the case, all comands must also be passed the `-a` flag, followed by the address+port where the daemon is running, and some commands might prompt for the daemons' api password

Initializing a wallet:
```
tfchainc wallet init
```
A password will be prompted with which the wallet file will be encrypted

Unlocking a wallete:
```
tfchainc wallet unlock
```
The password used to encrypt the wallet will be prompted

The wallet is now unlocked. Should there be the need to load a seed, then this can be accomplished as follows:

```
tfchainc wallet load seed
```
Then, the wallet password will be prompted, which can be provided on stdin
After the wallet password, the actual seed can be entered on stdin


Once the seed is correctly added, the daemon needs to be stopped
```
tfchainc stop
```
restarted, and unlocked again (don't init again).

The wallet is now unlocked with 2 seeds (the initial random one and the one loaded afterwards). If any of  the seeds has blockstakes, it will begin to create blocks

**Comment by LeeSmet** [comment]
There should be no need to manually manage connections to other nodes, as the daemon will contact the bootstrap nodes, and discover other viable nodes from there.

Should it be required, the command to add a peer is:

```
tfchainc gateway connect $addr:port
```

**Comment by LeeSmet** [comment]
Also, by default the daemon creates its data directories next to the binary. Should you desire to do this in another location, you can do so with the following flag:

```
-d, --tfchain-directory string   location of the tfchain director
```

e.g. `-d /storage`, this would create all persistent directories in the `/storage` directory

**Comment by khaledkbadr** [comment]
@LeeSmet Do the `tfchaind` and `tfchainc` have to start and stop together, or they are totally separated?

**Comment by LeeSmet** [comment]
Rivined is the daemon, which keepals running. Rivinec is the client, which exits after every command, it basically just sends an http request to the daemon

**Comment by khaledkbadr** [comment]
related sal implementation is here https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/zero_os/sal/Rivine.py

**Comment by despiegk** [comment]
the location is wrong

rivine has server part needs to be j.servers.rivine
client part on j.clients.rivine
